# Link checking
# https://github.com/dkhamsing/awesome_bot

os: linux

language: ruby

rvm: 2.7.0

before_script:
  - gem install awesome_bot

script:
  - awesome_bot --allow-dupe --skip-save-results --base-url https://github.com/nmstreethran/charts/blob/master/ --white-list travis-ci.org `find . -name "*.md"`
